import Foundation

/// Extra DIRECT rules for iOS light mode (no GeoSite). Keeps system & domestic apps working on VPN.
enum IosDirectDomains {
    static let privateIPRules: [String] = [
        "IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
        "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
        "IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
        "IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,169.254.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,224.0.0.0/4,DIRECT,no-resolve",
    ]

    /// Highest priority on iOS — WeChat image/voice upload uses CDN domains + bare IPs.
    /// Missing these → MATCH,PROXY → overseas node → 图片/文件发不出去.
    static let wechatPriorityRules: [String] = [
        "DOMAIN,localhost.weixin.qq.com,DIRECT",
        "DOMAIN-SUFFIX,weixin.qq.com,DIRECT",
        "DOMAIN-SUFFIX,weixin.com,DIRECT",
        "DOMAIN-SUFFIX,wechat.com,DIRECT",
        "DOMAIN-SUFFIX,servicewechat.com,DIRECT",
        "DOMAIN-SUFFIX,qq.com,DIRECT",
        "DOMAIN-SUFFIX,tenpay.com,DIRECT",
        "DOMAIN-SUFFIX,qpic.cn,DIRECT",
        "DOMAIN-SUFFIX,qlogo.cn,DIRECT",
        "DOMAIN-SUFFIX,gtimg.cn,DIRECT",
        "DOMAIN-SUFFIX,gtimg.com,DIRECT",
        "DOMAIN-SUFFIX,idqqimg.com,DIRECT",
        "DOMAIN-SUFFIX,myapp.com,DIRECT",
        "DOMAIN-SUFFIX,tencent.com,DIRECT",
        "DOMAIN-SUFFIX,tencent-cloud.net,DIRECT",
        "DOMAIN-SUFFIX,tencentcs.com,DIRECT",
        "DOMAIN-SUFFIX,qcloud.com,DIRECT",
        "DOMAIN-KEYWORD,weixin,DIRECT",
        "DOMAIN-KEYWORD,qpic,DIRECT",
        // Common Tencent / WeChat CDN & upload edge ranges (no-resolve: bare IP dials)
        "IP-CIDR,1.12.0.0/14,DIRECT,no-resolve",
        "IP-CIDR,14.17.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,14.18.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,14.19.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,14.116.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,43.154.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,58.247.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,58.251.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,59.37.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,101.226.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,101.227.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,109.244.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,111.30.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,113.96.0.0/12,DIRECT,no-resolve",
        "IP-CIDR,119.147.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,121.51.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,140.207.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,157.255.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,180.163.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,182.254.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.3.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.36.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.47.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.57.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.60.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.192.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.232.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,203.205.128.0/19,DIRECT,no-resolve",
        "IP-CIDR,211.95.0.0/16,DIRECT,no-resolve",
    ]

    static let rules: [String] = privateIPRules + [
        // Apple (GEOSITE,apple@cn stripped on iOS)
        "DOMAIN-SUFFIX,apple.com,DIRECT",
        "DOMAIN-SUFFIX,icloud.com,DIRECT",
        "DOMAIN-SUFFIX,cdn-apple.com,DIRECT",
        "DOMAIN-SUFFIX,mzstatic.com,DIRECT",
        "DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT",
        "DOMAIN-SUFFIX,apple-mapkit.com,DIRECT",
        // iOS system DoH — must not hit GOOGLE url-test (logs: dns.google.com resolve timeout).
        "DOMAIN,dns.google.com,DIRECT",
        "DOMAIN-SUFFIX,dns.google,DIRECT",
        // Apple CDN / Private Relay IPs (no SNI → otherwise MATCH,PROXY).
        "IP-CIDR,17.248.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,17.249.0.0/16,DIRECT,no-resolve",
        "DOMAIN-SUFFIX,ess.apple.com,DIRECT",
        "DOMAIN-SUFFIX,gs.apple.com,DIRECT",
        "DOMAIN-SUFFIX,me.com,DIRECT",
        "DOMAIN-SUFFIX,icloud-content.com,DIRECT",
        "DOMAIN,gateway.icloud.com,DIRECT",
        "DOMAIN,gsa.apple.com,DIRECT",
        // WeChat / QQ — also in wechatPriorityRules (prepended); keep here as safety net
        "DOMAIN-SUFFIX,qq.com,DIRECT",
        "DOMAIN-SUFFIX,weixin.qq.com,DIRECT",
        "DOMAIN-SUFFIX,weixin.com,DIRECT",
        "DOMAIN-SUFFIX,wechat.com,DIRECT",
        "DOMAIN-SUFFIX,tenpay.com,DIRECT",
        "DOMAIN-SUFFIX,qpic.cn,DIRECT",
        "DOMAIN-SUFFIX,qlogo.cn,DIRECT",
        "DOMAIN-SUFFIX,gtimg.cn,DIRECT",
        "DOMAIN-SUFFIX,gtimg.com,DIRECT",
        "DOMAIN-KEYWORD,weixin,DIRECT",
        // iOS / carrier / local discovery
        "DOMAIN-SUFFIX,local,DIRECT",
        "DOMAIN-SUFFIX,home.arpa,DIRECT",
        "DOMAIN-SUFFIX,router,DIRECT",
        "DOMAIN-SUFFIX,localhost,DIRECT",
        // Common CN backends not always in smart list
        "DOMAIN-SUFFIX,163.com,DIRECT",
        "DOMAIN-SUFFIX,127.net,DIRECT",
        "DOMAIN-SUFFIX,youdao.com,DIRECT",
        "DOMAIN-SUFFIX,95516.com,DIRECT",
        "DOMAIN-SUFFIX,unionpay.com,DIRECT",
        "DOMAIN-SUFFIX,10086.cn,DIRECT",
        "DOMAIN-SUFFIX,189.cn,DIRECT",
        "DOMAIN-SUFFIX,chinamobile.com,DIRECT",
        "DOMAIN-SUFFIX,chinaunicom.com,DIRECT",
        "DOMAIN-SUFFIX,ctrip.com,DIRECT",
        "DOMAIN-SUFFIX,amap.com,DIRECT",
        "DOMAIN-SUFFIX,autonavi.com,DIRECT",
        "DOMAIN-SUFFIX,baidu.com,DIRECT",
        "DOMAIN-SUFFIX,bdstatic.com,DIRECT",
        "DOMAIN-SUFFIX,bdimg.com,DIRECT",
        "DOMAIN-SUFFIX,baidubce.com,DIRECT",
        "DOMAIN-SUFFIX,bcebos.com,DIRECT",
        "DOMAIN-SUFFIX,baidu-int.com,DIRECT",
        "DOMAIN-SUFFIX,aliyun.com,DIRECT",
        "DOMAIN-SUFFIX,alicdn.com,DIRECT",
        "DOMAIN-SUFFIX,taobao.com,DIRECT",
        "DOMAIN-SUFFIX,alipay.com,DIRECT",
        "DOMAIN-SUFFIX,jd.com,DIRECT",
        "DOMAIN-SUFFIX,bilibili.com,DIRECT",
        "DOMAIN-SUFFIX,bilivideo.com,DIRECT",
        "DOMAIN-SUFFIX,zhihu.com,DIRECT",
        "DOMAIN-SUFFIX,netease.com,DIRECT",
    ]
}
