import Foundation

/// Extra DIRECT rules for iOS light mode (no GeoSite). Keeps system & domestic apps working on VPN.
enum IosDirectDomains {
    static let privateIPRules: [String] = [
        "IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
        "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
        "IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
        "IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,169.254.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,224.0.0.0/4,DIRECT,no-resolve",
    ]

    /// DNS resolvers used by BashX iOS DNS — must never go through PROXY.
    static let dnsBootstrapDirectRules: [String] = [
        "IP-CIDR,223.5.5.5/32,DIRECT,no-resolve",
        "IP-CIDR,223.6.6.6/32,DIRECT,no-resolve",
        "IP-CIDR,119.29.29.29/32,DIRECT,no-resolve",
        "IP-CIDR,1.12.12.12/32,DIRECT,no-resolve",
        "IP-CIDR,114.114.114.114/32,DIRECT,no-resolve",
        "DOMAIN-SUFFIX,alidns.com,DIRECT",
        "DOMAIN-SUFFIX,doh.pub,DIRECT",
        "DOMAIN,dns.alidns.com,DIRECT",
        "DOMAIN,doh.pub,DIRECT",
    ]

    /// 淘宝 / 闲鱼 / 国内电商 — must beat MATCH,PROXY (goofish 等不在旧列表里会全进节点).
    static let ecommercePriorityRules: [String] = [
        // 闲鱼（主域已迁 goofish；旧 idlefish / 2.taobao 仍在用）
        "DOMAIN-SUFFIX,goofish.com,DIRECT",
        "DOMAIN-SUFFIX,goofish.pro,DIRECT",
        "DOMAIN-SUFFIX,idlefish.com,DIRECT",
        "DOMAIN-SUFFIX,xianyu.com,DIRECT",
        "DOMAIN-KEYWORD,goofish,DIRECT",
        "DOMAIN-KEYWORD,xianyu,DIRECT",
        "DOMAIN-KEYWORD,idlefish,DIRECT",
        // 淘宝 / 天猫 / 支付宝 / 阿里 CDN（含 HTTPDNS，勿 REJECT）
        "DOMAIN,httpdns.alicdn.com,DIRECT",
        "DOMAIN-SUFFIX,httpdns.alicdn.com,DIRECT",
        "DOMAIN-SUFFIX,taobao.com,DIRECT",
        "DOMAIN-SUFFIX,tmall.com,DIRECT",
        "DOMAIN-SUFFIX,tmall.hk,DIRECT",
        "DOMAIN-SUFFIX,alicdn.com,DIRECT",
        "DOMAIN-SUFFIX,aliyuncs.com,DIRECT",
        "DOMAIN-SUFFIX,alibaba.com,DIRECT",
        "DOMAIN-SUFFIX,alibaba-inc.com,DIRECT",
        "DOMAIN-SUFFIX,alipay.com,DIRECT",
        "DOMAIN-SUFFIX,alipayobjects.com,DIRECT",
        "DOMAIN-SUFFIX,tb.cn,DIRECT",
        "DOMAIN-SUFFIX,tbcdn.cn,DIRECT",
        "DOMAIN-SUFFIX,tbcache.com,DIRECT",
        "DOMAIN-SUFFIX,mmstat.com,DIRECT",
        "DOMAIN-SUFFIX,tanx.com,DIRECT",
        "DOMAIN-KEYWORD,taobao,DIRECT",
        "DOMAIN-KEYWORD,alicdn,DIRECT",
        "DOMAIN-KEYWORD,alipay,DIRECT",
        // 京东 / 拼多多 / 唯品会 / 得物 / 苏宁 等
        "DOMAIN-SUFFIX,jd.com,DIRECT",
        "DOMAIN-SUFFIX,jd.hk,DIRECT",
        "DOMAIN-SUFFIX,jdpay.com,DIRECT",
        "DOMAIN-SUFFIX,360buyimg.com,DIRECT",
        "DOMAIN-SUFFIX,pinduoduo.com,DIRECT",
        "DOMAIN-SUFFIX,yangkeduo.com,DIRECT",
        "DOMAIN-SUFFIX,suning.com,DIRECT",
        "DOMAIN-SUFFIX,vip.com,DIRECT",
        "DOMAIN-SUFFIX,vipstatic.com,DIRECT",
        "DOMAIN-SUFFIX,dewu.com,DIRECT",
        "DOMAIN-SUFFIX,poizon.com,DIRECT",
        "DOMAIN-SUFFIX,kaola.com,DIRECT",
        "DOMAIN-SUFFIX,fliggy.com,DIRECT",
        "DOMAIN-SUFFIX,cainiao.com,DIRECT",
        "DOMAIN-SUFFIX,ele.me,DIRECT",
        "DOMAIN-SUFFIX,elemecdn.com,DIRECT",
    ]

    /// TikTok（国际版）— 与大陆抖音完全分开。
    /// 抖音核心 API 用 snssdk.com → 必须 DIRECT；TikTok 用 isnssdk / sgsnssdk / tiktok* / byteoversea。
    /// Twitch-style: 少量 QUIC kill（节点黑洞 UDP/443 会卡死 App）。
    static let tiktokPriorityRules: [String] = [
        "AND,((DOMAIN-SUFFIX,tiktok.com),(NETWORK,UDP),(DST-PORT,443)),REJECT",
        "AND,((DOMAIN-SUFFIX,tiktokv.com),(NETWORK,UDP),(DST-PORT,443)),REJECT",
        "AND,((DOMAIN-SUFFIX,tiktokcdn.com),(NETWORK,UDP),(DST-PORT,443)),REJECT",
        "DOMAIN-SUFFIX,tiktok.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktok-row.net,TIKTOK",
        "DOMAIN-SUFFIX,tiktokv.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokv.us,TIKTOK",
        "DOMAIN-SUFFIX,tiktokv.eu,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn-us.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn-eu.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn-in.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokd.net,TIKTOK",
        "DOMAIN-SUFFIX,tiktokd.org,TIKTOK",
        "DOMAIN-SUFFIX,tiktokmusic.app,TIKTOK",
        "DOMAIN-SUFFIX,tik-tokapi.com,TIKTOK",
        "DOMAIN-SUFFIX,ttlivecdn.com,TIKTOK",
        "DOMAIN-SUFFIX,ttlstatic.com,TIKTOK",
        "DOMAIN-SUFFIX,ttcdn-us.com,TIKTOK",
        "DOMAIN-SUFFIX,ttwebview.com,TIKTOK",
        "DOMAIN-SUFFIX,ttwstatic.com,TIKTOK",
        "DOMAIN-SUFFIX,ttoversea.net,TIKTOK",
        "DOMAIN-SUFFIX,ttoverseaus.net,TIKTOK",
        "DOMAIN-SUFFIX,musical.ly,TIKTOK",
        "DOMAIN-SUFFIX,muscdn.com,TIKTOK",
        "DOMAIN-SUFFIX,byteoversea.com,TIKTOK",
        "DOMAIN-SUFFIX,byteoversea.net,TIKTOK",
        "DOMAIN-SUFFIX,byteintlapi.com,TIKTOK",
        "DOMAIN-SUFFIX,byteintl.net,TIKTOK",
        "DOMAIN-SUFFIX,bytevcloudapi.com,TIKTOK",
        "DOMAIN-SUFFIX,bytegecko.com,TIKTOK",
        "DOMAIN-SUFFIX,bytegecko-i18n.com,TIKTOK",
        "DOMAIN-SUFFIX,bytedapm.com,TIKTOK",
        "DOMAIN-SUFFIX,byteeffecttos-g.com,TIKTOK",
        "DOMAIN-SUFFIX,bytefcdn-oversea.com,TIKTOK",
        "DOMAIN-SUFFIX,bytefcdn-ttpeu.com,TIKTOK",
        "DOMAIN-SUFFIX,bytetcdn.com,TIKTOK",
        "DOMAIN-SUFFIX,bytedanceapi.com,TIKTOK",
        "DOMAIN-SUFFIX,worldfcdn.com,TIKTOK",
        "DOMAIN-SUFFIX,worldfcdn2.com,TIKTOK",
        "DOMAIN-SUFFIX,ibyteimg.com,TIKTOK",
        "DOMAIN-SUFFIX,ibytedtos.com,TIKTOK",
        "DOMAIN-SUFFIX,ipstatp.com,TIKTOK",
        "DOMAIN-SUFFIX,sgpstatp.com,TIKTOK",
        // 国际版 snssdk 变体 — 不含 snssdk.com（那是大陆抖音）
        "DOMAIN-SUFFIX,sgsnssdk.com,TIKTOK",
        "DOMAIN-SUFFIX,isnssdk.com,TIKTOK",
        "DOMAIN-SUFFIX,vodupload.com,TIKTOK",
        "DOMAIN-SUFFIX,yhgfb-static.com,TIKTOK",
        "DOMAIN-SUFFIX,goofy.app,TIKTOK",
        "DOMAIN-SUFFIX,wsdvs.com,TIKTOK",
        "DOMAIN-SUFFIX,capcut.com,TIKTOK",
        "DOMAIN-SUFFIX,capcutapi.com,TIKTOK",
        "DOMAIN-SUFFIX,capcutapi.us,TIKTOK",
        "DOMAIN-SUFFIX,capcutcdn-us.com,TIKTOK",
        "DOMAIN-SUFFIX,capcutstatic.com,TIKTOK",
        "DOMAIN,p16-tiktokcdn-com.akamaized.net,TIKTOK",
        "DOMAIN,v16-tiktokcdn-com.akamaized.net,TIKTOK",
        "DOMAIN,lf16-effectcdn.byteeffecttos-g.com,TIKTOK",
        "DOMAIN,lf16-pkgcdn.pitaya-clientai.com,TIKTOK",
        "DOMAIN-KEYWORD,ttcdn,TIKTOK",
        "DOMAIN-KEYWORD,tt.byteimg,TIKTOK",
        "DOMAIN-KEYWORD,tiktok,TIKTOK",
        "DOMAIN-KEYWORD,tiktokcdn,TIKTOK",
        "DOMAIN-KEYWORD,musical.ly,TIKTOK",
        "DOMAIN-KEYWORD,byteoversea,TIKTOK",
        "DOMAIN-KEYWORD,ttlivecdn,TIKTOK",
        "DOMAIN-KEYWORD,isnssdk,TIKTOK",
        "DOMAIN-KEYWORD,sgsnssdk,TIKTOK",
        "DOMAIN-KEYWORD,bytefcdn,TIKTOK",
        "DOMAIN-KEYWORD,worldfcdn,TIKTOK",
    ]

    /// iOS: keep TIKTOK policy (Asia group). Mac/shared callers may still remap.
    static func tiktokRulesForPlatform(forIOS: Bool) -> [String] {
        // Always keep TIKTOK group — collapsing to PROXY broke TikTok when user
        // picked a US/ME leaf (TikTok geo-blocks many DC exits).
        _ = forIOS
        return tiktokPriorityRules
    }

    /// AnyDesk — must beat DOMAIN-SUFFIX,cn,DIRECT (*.anydesk.com.cn was swallowed).
    /// Default DIRECT: many airport exits black-hole AnyDesk →「not connected to the server」.
    /// User can switch to PROXY in 应用分流 if DIRECT is blocked by GFW.
    static let anydeskPriorityRules: [String] = [
        "PROCESS-NAME,AnyDesk,DIRECT",
        "PROCESS-PATH,*AnyDesk.app/Contents/MacOS/*,DIRECT",
        "DOMAIN-SUFFIX,anydesk.com,DIRECT",
        "DOMAIN-SUFFIX,anydesk.com.cn,DIRECT",
        "DOMAIN-SUFFIX,net.anydesk.com,DIRECT",
        "DOMAIN-SUFFIX,net.anydesk.com.cn,DIRECT",
        "DOMAIN-KEYWORD,anydesk,DIRECT",
    ]

    /// 小红书 App — 国内直连，勿进 MATCH,PROXY.
    static let xiaohongshuPriorityRules: [String] = [
        "DOMAIN-SUFFIX,xiaohongshu.com,DIRECT",
        "DOMAIN-SUFFIX,xhscdn.com,DIRECT",
        "DOMAIN-SUFFIX,xhscdn.net,DIRECT",
        "DOMAIN-SUFFIX,xhslink.com,DIRECT",
        "DOMAIN-SUFFIX,fengkongcloud.com,DIRECT",
        "DOMAIN-SUFFIX,rednote.com,DIRECT",
        "DOMAIN-KEYWORD,xiaohongshu,DIRECT",
        "DOMAIN-KEYWORD,xhscdn,DIRECT",
        "DOMAIN-KEYWORD,xhslink,DIRECT",
        "DOMAIN-KEYWORD,rednote,DIRECT",
    ]

    /// 银行关键词 / 常见银行域名 — 一律本地直连.
    static let bankPriorityRules: [String] = [
        "DOMAIN-SUFFIX,bank,DIRECT",
        "DOMAIN-KEYWORD,bank,DIRECT",
        "DOMAIN-KEYWORD,银行,DIRECT",
        "DOMAIN-KEYWORD,yinhang,DIRECT",
        "DOMAIN-SUFFIX,icbc.com.cn,DIRECT",
        "DOMAIN-SUFFIX,icbc.com,DIRECT",
        "DOMAIN-SUFFIX,95588.com,DIRECT",
        "DOMAIN-SUFFIX,ccb.com,DIRECT",
        "DOMAIN-SUFFIX,abchina.com,DIRECT",
        "DOMAIN-SUFFIX,abchina.com.cn,DIRECT",
        "DOMAIN-SUFFIX,bankcomm.com,DIRECT",
        "DOMAIN-SUFFIX,boc.cn,DIRECT",
        "DOMAIN-SUFFIX,bankofchina.com,DIRECT",
        "DOMAIN-SUFFIX,cmbchina.com,DIRECT",
        "DOMAIN-SUFFIX,cmb.com.cn,DIRECT",
        "DOMAIN-SUFFIX,cib.com.cn,DIRECT",
        "DOMAIN-SUFFIX,spdb.com.cn,DIRECT",
        "DOMAIN-SUFFIX,cebbank.com,DIRECT",
        "DOMAIN-SUFFIX,cmbc.com.cn,DIRECT",
        "DOMAIN-SUFFIX,psbc.com,DIRECT",
        "DOMAIN-SUFFIX,citicbank.com,DIRECT",
        "DOMAIN-SUFFIX,hxb.com.cn,DIRECT",
        "DOMAIN-SUFFIX,cgbchina.com.cn,DIRECT",
        "DOMAIN-SUFFIX,bankofbeijing.com.cn,DIRECT",
        "DOMAIN-SUFFIX,bosc.cn,DIRECT",
        "DOMAIN-SUFFIX,hzbank.com.cn,DIRECT",
        "DOMAIN-SUFFIX,njcb.com.cn,DIRECT",
        "DOMAIN-SUFFIX,nbcb.com.cn,DIRECT",
        "DOMAIN-SUFFIX,czbank.com,DIRECT",
        "DOMAIN-SUFFIX,hsbank.com.cn,DIRECT",
        "DOMAIN-SUFFIX,bankofshanghai.com,DIRECT",
        "DOMAIN-SUFFIX,pingan.com,DIRECT",
        "DOMAIN-SUFFIX,1qianbao.com,DIRECT",
        "DOMAIN-SUFFIX,webank.com,DIRECT",
        "DOMAIN-SUFFIX,mybank.cn,DIRECT",
        "DOMAIN-SUFFIX,chinapay.com,DIRECT",
        "DOMAIN-SUFFIX,yeepay.com,DIRECT",
        "DOMAIN-SUFFIX,unionpay.com,DIRECT",
        "DOMAIN-SUFFIX,95516.com,DIRECT",
        "DOMAIN-SUFFIX,tenpay.com,DIRECT",
        "DOMAIN-SUFFIX,bankofchina.com.hk,DIRECT",
        "DOMAIN-SUFFIX,hangseng.com,DIRECT",
        "DOMAIN-SUFFIX,hsbc.com.hk,DIRECT",
        "DOMAIN-SUFFIX,hsbc.com.cn,DIRECT",
        "DOMAIN-SUFFIX,bochk.com,DIRECT",
        "DOMAIN-SUFFIX,livibank.com,DIRECT",
        "DOMAIN-SUFFIX,welab.bank,DIRECT",
    ]

    /// 抖音 / 头条 / 西瓜 — must beat MATCH,PROXY（缺 zijieapi 等会进节点→国内接口拒海外 IP）.
    /// TikTok 国际域名见 tiktokPriorityRules（须排在本列表之前）.
    /// 大陆抖音 — 一律 DIRECT，绝不进代理（与国际 TikTok 无关）。
    static let douyinPriorityRules: [String] = [
        "DOMAIN-SUFFIX,zijieapi.com,DIRECT",
        "DOMAIN-SUFFIX,ecombdapi.com,DIRECT",
        "DOMAIN-SUFFIX,amemv.com,DIRECT",
        "DOMAIN-SUFFIX,douyin.com,DIRECT",
        "DOMAIN-SUFFIX,douyincdn.com,DIRECT",
        "DOMAIN-SUFFIX,douyinpic.com,DIRECT",
        "DOMAIN-SUFFIX,douyinvod.com,DIRECT",
        "DOMAIN-SUFFIX,douyinliving.com,DIRECT",
        "DOMAIN-SUFFIX,bytedance.com,DIRECT",
        "DOMAIN-SUFFIX,bytedance.net,DIRECT",
        "DOMAIN-SUFFIX,byteimg.com,DIRECT",
        "DOMAIN-SUFFIX,bytescm.com,DIRECT",
        "DOMAIN-SUFFIX,byteacctimg.com,DIRECT",
        "DOMAIN-SUFFIX,pstatp.com,DIRECT",
        // 大陆抖音主 API — 勿进 TIKTOK/PROXY
        "DOMAIN-SUFFIX,snssdk.com,DIRECT",
        "DOMAIN-SUFFIX,ixigua.com,DIRECT",
        "DOMAIN-SUFFIX,toutiao.com,DIRECT",
        "DOMAIN-SUFFIX,toutiaovod.com,DIRECT",
        "DOMAIN-SUFFIX,toutiaostatic.com,DIRECT",
        "DOMAIN-SUFFIX,huoshan.com,DIRECT",
        "DOMAIN-SUFFIX,huoshanstatic.com,DIRECT",
        "DOMAIN-SUFFIX,volces.com,DIRECT",
        "DOMAIN-SUFFIX,volccdn.com,DIRECT",
        "DOMAIN-SUFFIX,ulikecam.com,DIRECT",
        "DOMAIN-SUFFIX,faceu.mobi,DIRECT",
        "DOMAIN-KEYWORD,douyin,DIRECT",
        "DOMAIN-KEYWORD,amemv,DIRECT",
        "DOMAIN-KEYWORD,zijieapi,DIRECT",
        // 不用 DOMAIN-KEYWORD,snssdk — 会误伤 isnssdk / sgsnssdk（TikTok）
    ]

    /// Highest priority on iOS — WeChat image/voice upload uses CDN domains + bare IPs.
    /// Missing these → MATCH,PROXY → overseas node → 图片/文件发不出去.
    static let wechatPriorityRules: [String] = [
        "DOMAIN,localhost.weixin.qq.com,DIRECT",
        "DOMAIN-SUFFIX,weixin.qq.com,DIRECT",
        "DOMAIN-SUFFIX,weixin.com,DIRECT",
        "DOMAIN-SUFFIX,wechat.com,DIRECT",
        "DOMAIN-SUFFIX,servicewechat.com,DIRECT",
        "DOMAIN-SUFFIX,qq.com,DIRECT",
        "DOMAIN-SUFFIX,tenpay.com,DIRECT",
        "DOMAIN-SUFFIX,qpic.cn,DIRECT",
        "DOMAIN-SUFFIX,qlogo.cn,DIRECT",
        "DOMAIN-SUFFIX,gtimg.cn,DIRECT",
        "DOMAIN-SUFFIX,gtimg.com,DIRECT",
        "DOMAIN-SUFFIX,idqqimg.com,DIRECT",
        "DOMAIN-SUFFIX,myapp.com,DIRECT",
        "DOMAIN-SUFFIX,tencent.com,DIRECT",
        "DOMAIN-SUFFIX,tencent-cloud.net,DIRECT",
        "DOMAIN-SUFFIX,tencentcs.com,DIRECT",
        "DOMAIN-SUFFIX,qcloud.com,DIRECT",
        "DOMAIN-KEYWORD,weixin,DIRECT",
        "DOMAIN-KEYWORD,qpic,DIRECT",
        // Common Tencent / WeChat CDN & upload edge ranges (no-resolve: bare IP dials)
        "IP-CIDR,1.12.0.0/14,DIRECT,no-resolve",
        "IP-CIDR,14.17.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,14.18.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,14.19.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,14.116.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,43.154.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,58.247.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,58.251.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,59.37.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,101.226.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,101.227.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,109.244.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,111.30.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,113.96.0.0/12,DIRECT,no-resolve",
        "IP-CIDR,119.147.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,121.51.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,140.207.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,157.255.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,180.163.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,182.254.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.3.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.36.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.47.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.57.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.60.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.192.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,183.232.0.0/16,DIRECT,no-resolve",
        "IP-CIDR,203.205.128.0/19,DIRECT,no-resolve",
        "IP-CIDR,211.95.0.0/16,DIRECT,no-resolve",
    ]

    static let rules: [String] = privateIPRules + [
        // Apple (GEOSITE,apple@cn stripped on iOS)
        "DOMAIN-SUFFIX,apple.com,DIRECT",
        "DOMAIN-SUFFIX,icloud.com,DIRECT",
        "DOMAIN-SUFFIX,cdn-apple.com,DIRECT",
        "DOMAIN-SUFFIX,mzstatic.com,DIRECT",
        "DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT",
        "DOMAIN-SUFFIX,apple-mapkit.com,DIRECT",
        // iOS system DoH — must not hit GOOGLE url-test (logs: dns.google.com resolve timeout).
        "DOMAIN,dns.google.com,DIRECT",
        "DOMAIN-SUFFIX,dns.google,DIRECT",
        // Apple CDN / Private Relay IPs (no SNI → otherwise MATCH,PROXY).
        // Do NOT include 17.249/17.252 — those are APNs and must stay on APNS group.
        "IP-CIDR,17.248.0.0/16,DIRECT,no-resolve",
        "DOMAIN-SUFFIX,ess.apple.com,DIRECT",
        "DOMAIN-SUFFIX,gs.apple.com,DIRECT",
        "DOMAIN-SUFFIX,me.com,DIRECT",
        "DOMAIN-SUFFIX,icloud-content.com,DIRECT",
        "DOMAIN,gateway.icloud.com,DIRECT",
        "DOMAIN,gsa.apple.com,DIRECT",
        // WeChat / QQ — also in wechatPriorityRules (prepended); keep here as safety net
        "DOMAIN-SUFFIX,qq.com,DIRECT",
        "DOMAIN-SUFFIX,weixin.qq.com,DIRECT",
        "DOMAIN-SUFFIX,weixin.com,DIRECT",
        "DOMAIN-SUFFIX,wechat.com,DIRECT",
        "DOMAIN-SUFFIX,tenpay.com,DIRECT",
        "DOMAIN-SUFFIX,qpic.cn,DIRECT",
        "DOMAIN-SUFFIX,qlogo.cn,DIRECT",
        "DOMAIN-SUFFIX,gtimg.cn,DIRECT",
        "DOMAIN-SUFFIX,gtimg.com,DIRECT",
        "DOMAIN-KEYWORD,weixin,DIRECT",
        // iOS / carrier / local discovery
        "DOMAIN-SUFFIX,local,DIRECT",
        "DOMAIN-SUFFIX,home.arpa,DIRECT",
        "DOMAIN-SUFFIX,router,DIRECT",
        "DOMAIN-SUFFIX,localhost,DIRECT",
        // Common CN backends not always in smart list
        "DOMAIN-SUFFIX,163.com,DIRECT",
        "DOMAIN-SUFFIX,127.net,DIRECT",
        "DOMAIN-SUFFIX,youdao.com,DIRECT",
        "DOMAIN-SUFFIX,95516.com,DIRECT",
        "DOMAIN-SUFFIX,unionpay.com,DIRECT",
        "DOMAIN-SUFFIX,10086.cn,DIRECT",
        "DOMAIN-SUFFIX,189.cn,DIRECT",
        "DOMAIN-SUFFIX,chinamobile.com,DIRECT",
        "DOMAIN-SUFFIX,chinaunicom.com,DIRECT",
        "DOMAIN-SUFFIX,ctrip.com,DIRECT",
        "DOMAIN-SUFFIX,amap.com,DIRECT",
        "DOMAIN-SUFFIX,autonavi.com,DIRECT",
        "DOMAIN-SUFFIX,baidu.com,DIRECT",
        "DOMAIN-SUFFIX,bdstatic.com,DIRECT",
        "DOMAIN-SUFFIX,bdimg.com,DIRECT",
        "DOMAIN-SUFFIX,baidubce.com,DIRECT",
        "DOMAIN-SUFFIX,bcebos.com,DIRECT",
        "DOMAIN-SUFFIX,baidu-int.com,DIRECT",
        "DOMAIN-SUFFIX,aliyun.com,DIRECT",
        "DOMAIN-SUFFIX,alicdn.com,DIRECT",
        "DOMAIN-SUFFIX,taobao.com,DIRECT",
        "DOMAIN-SUFFIX,tmall.com,DIRECT",
        "DOMAIN-SUFFIX,alipay.com,DIRECT",
        "DOMAIN-SUFFIX,goofish.com,DIRECT",
        "DOMAIN-SUFFIX,idlefish.com,DIRECT",
        "DOMAIN-SUFFIX,jd.com,DIRECT",
        "DOMAIN-SUFFIX,pinduoduo.com,DIRECT",
        "DOMAIN-SUFFIX,yangkeduo.com,DIRECT",
        "DOMAIN-SUFFIX,vip.com,DIRECT",
        "DOMAIN-SUFFIX,bilibili.com,DIRECT",
        "DOMAIN-SUFFIX,bilivideo.com,DIRECT",
        "DOMAIN-SUFFIX,zhihu.com,DIRECT",
        "DOMAIN-SUFFIX,netease.com,DIRECT",
    ]
}
