import Foundation

/// Domain rules for iOS light mode (no GeoSite DB). Inserted before MATCH,PROXY.
enum IosProxyDomains {
    /// Telegram DC CIDRs — iOS strips GEOIP,telegram; real IPs otherwise need these CIDRs.
    static let telegramIPRules: [String] = [
        "IP-CIDR,149.154.160.0/20,TELEGRAM,no-resolve",
        "IP-CIDR,91.108.0.0/16,TELEGRAM,no-resolve",
        "IP-CIDR,91.105.192.0/23,TELEGRAM,no-resolve",
        "IP-CIDR,185.76.151.0/24,TELEGRAM,no-resolve",
        // Media / CDN ranges Telegram dials by bare IP
        "IP-CIDR,95.161.64.0/20,TELEGRAM,no-resolve",
        // DC IPv6 — iOS TUN only pulls these prefixes in (see PacketTunnelProvider)
        "IP-CIDR6,2001:67c:4e8::/48,TELEGRAM,no-resolve",
        "IP-CIDR6,2001:b28:f23c::/48,TELEGRAM,no-resolve",
        "IP-CIDR6,2001:b28:f23d::/48,TELEGRAM,no-resolve",
        "IP-CIDR6,2001:b28:f23f::/48,TELEGRAM,no-resolve",
    ]

    static let rules: [String] = telegramIPRules + [
        // Google / YouTube → GOOGLE (falls back to PROXY in patchIOSPassthroughRules)
        "DOMAIN-SUFFIX,google.com,GOOGLE",
        "DOMAIN-SUFFIX,google.com.hk,GOOGLE",
        "DOMAIN-SUFFIX,google.cn,GOOGLE",
        "DOMAIN-SUFFIX,googleapis.com,GOOGLE",
        "DOMAIN-SUFFIX,googleapis.cn,GOOGLE",
        "DOMAIN-SUFFIX,gstatic.com,GOOGLE",
        "DOMAIN-SUFFIX,gstatic.cn,GOOGLE",
        "DOMAIN-SUFFIX,googleusercontent.com,GOOGLE",
        "DOMAIN-SUFFIX,googlesyndication.com,GOOGLE",
        "DOMAIN-SUFFIX,googlevideo.com,GOOGLE",
        "DOMAIN-SUFFIX,youtube.com,GOOGLE",
        "DOMAIN-SUFFIX,youtu.be,GOOGLE",
        "DOMAIN-SUFFIX,ytimg.com,GOOGLE",
        "DOMAIN-SUFFIX,ggpht.com,GOOGLE",
        "DOMAIN-SUFFIX,gmail.com,GOOGLE",
        "DOMAIN-SUFFIX,android.com,GOOGLE",
        "DOMAIN-SUFFIX,gvt1.com,GOOGLE",
        "DOMAIN-SUFFIX,gvt2.com,GOOGLE",
        "DOMAIN-KEYWORD,google,GOOGLE",
        "DOMAIN-KEYWORD,youtube,GOOGLE",
        // Social / chat
        "DOMAIN-SUFFIX,twitter.com,PROXY",
        "DOMAIN-SUFFIX,x.com,PROXY",
        "DOMAIN-SUFFIX,twimg.com,PROXY",
        "DOMAIN-SUFFIX,t.co,PROXY",
        "DOMAIN-KEYWORD,twitter,PROXY",
        "DOMAIN-SUFFIX,facebook.com,PROXY",
        "DOMAIN-SUFFIX,fbcdn.net,PROXY",
        "DOMAIN-SUFFIX,instagram.com,PROXY",
        "DOMAIN-SUFFIX,cdninstagram.com,PROXY",
        "DOMAIN-SUFFIX,whatsapp.com,PROXY",
        "DOMAIN-SUFFIX,whatsapp.net,PROXY",
        "DOMAIN-SUFFIX,telegram.org,TELEGRAM",
        "DOMAIN-SUFFIX,telegram-cdn.org,TELEGRAM",
        "DOMAIN-SUFFIX,cdn-telegram.org,TELEGRAM",
        "DOMAIN-SUFFIX,telesco.pe,TELEGRAM",
        "DOMAIN-SUFFIX,t.me,TELEGRAM",
        "DOMAIN-SUFFIX,graph.org,TELEGRAM",
        "DOMAIN-SUFFIX,tdesktop.com,TELEGRAM",
        "DOMAIN-KEYWORD,telegram,TELEGRAM",
        "DOMAIN-SUFFIX,discord.com,PROXY",
        "DOMAIN-SUFFIX,discordapp.com,PROXY",
        // Dev / AI
        "DOMAIN-SUFFIX,github.com,PROXY",
        "DOMAIN-SUFFIX,githubusercontent.com,PROXY",
        "DOMAIN-SUFFIX,githubassets.com,PROXY",
        "DOMAIN-SUFFIX,cursor.sh,CURSOR",
        "DOMAIN-SUFFIX,cursor.com,CURSOR",
        "DOMAIN-SUFFIX,cursorapi.com,CURSOR",
        "DOMAIN-SUFFIX,cursor-cdn.com,CURSOR",
        "DOMAIN-SUFFIX,cursorvm.com,CURSOR",
        "DOMAIN-SUFFIX,anysphere.co,CURSOR",
        "DOMAIN-SUFFIX,anysphere.com,CURSOR",
        "DOMAIN-SUFFIX,anysphere.tech,CURSOR",
        "DOMAIN-KEYWORD,gcpp.cursor,CURSOR",
        "DOMAIN-SUFFIX,openai.com,PROXY",
        "DOMAIN-SUFFIX,chatgpt.com,PROXY",
        "DOMAIN-SUFFIX,anthropic.com,PROXY",
        "DOMAIN-SUFFIX,claude.ai,PROXY",
        // Media
        "DOMAIN-SUFFIX,netflix.com,PROXY",
        "DOMAIN-SUFFIX,nflxvideo.net,PROXY",
        "DOMAIN-SUFFIX,spotify.com,PROXY",
        "DOMAIN-SUFFIX,tiktok.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokv.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn-us.com,TIKTOK",
        "DOMAIN-SUFFIX,ttlivecdn.com,TIKTOK",
        "DOMAIN-SUFFIX,musical.ly,TIKTOK",
        "DOMAIN-SUFFIX,byteoversea.com,TIKTOK",
        "DOMAIN-SUFFIX,ibyteimg.com,TIKTOK",
        "DOMAIN-SUFFIX,ibytedtos.com,TIKTOK",
        "DOMAIN-KEYWORD,tiktok,TIKTOK",
        "DOMAIN-KEYWORD,byteoversea,TIKTOK",
        "DOMAIN-SUFFIX,reddit.com,PROXY",
        "DOMAIN-SUFFIX,redd.it,PROXY",
        // Common blocked
        "DOMAIN-SUFFIX,wikipedia.org,PROXY",
        "DOMAIN-SUFFIX,medium.com,PROXY",
        "DOMAIN-SUFFIX,dropbox.com,PROXY",
        "DOMAIN-SUFFIX,cloudflare.com,PROXY",
        "DOMAIN-SUFFIX,cloudfront.net,PROXY",
    ]
}
