import Foundation

/// Domain rules for iOS light mode (no GeoSite DB). Inserted before MATCH,PROXY.
enum IosProxyDomains {
    /// Telegram DC CIDRs — iOS strips GEOIP,telegram; real IPs otherwise need these CIDRs.
    static let telegramIPRules: [String] = [
        "IP-CIDR,149.154.160.0/20,TELEGRAM,no-resolve",
        "IP-CIDR,91.108.0.0/16,TELEGRAM,no-resolve",
        "IP-CIDR,91.105.192.0/23,TELEGRAM,no-resolve",
        "IP-CIDR,185.76.151.0/24,TELEGRAM,no-resolve",
        // Media / CDN ranges Telegram dials by bare IP
        "IP-CIDR,95.161.64.0/20,TELEGRAM,no-resolve",
        // DC IPv6 — iOS TUN only pulls these prefixes in (see PacketTunnelProvider)
        "IP-CIDR6,2001:67c:4e8::/48,TELEGRAM,no-resolve",
        "IP-CIDR6,2001:b28:f23c::/48,TELEGRAM,no-resolve",
        "IP-CIDR6,2001:b28:f23d::/48,TELEGRAM,no-resolve",
        "IP-CIDR6,2001:b28:f23f::/48,TELEGRAM,no-resolve",
    ]

    static let rules: [String] = telegramIPRules + [
        // Google / YouTube → GOOGLE (falls back to PROXY in patchIOSPassthroughRules)
        "DOMAIN-SUFFIX,google.com,GOOGLE",
        "DOMAIN-SUFFIX,google.com.hk,GOOGLE",
        "DOMAIN-SUFFIX,google.cn,GOOGLE",
        "DOMAIN-SUFFIX,googleapis.com,GOOGLE",
        "DOMAIN-SUFFIX,googleapis.cn,GOOGLE",
        "DOMAIN-SUFFIX,gstatic.com,GOOGLE",
        "DOMAIN-SUFFIX,gstatic.cn,GOOGLE",
        "DOMAIN-SUFFIX,googleusercontent.com,GOOGLE",
        "DOMAIN-SUFFIX,googlesyndication.com,GOOGLE",
        "DOMAIN-SUFFIX,googlevideo.com,GOOGLE",
        "DOMAIN-SUFFIX,youtube.com,GOOGLE",
        "DOMAIN-SUFFIX,youtu.be,GOOGLE",
        "DOMAIN-SUFFIX,ytimg.com,GOOGLE",
        "DOMAIN-SUFFIX,ggpht.com,GOOGLE",
        "DOMAIN-SUFFIX,gmail.com,GOOGLE",
        "DOMAIN-SUFFIX,android.com,GOOGLE",
        "DOMAIN-SUFFIX,gvt1.com,GOOGLE",
        "DOMAIN-SUFFIX,gvt2.com,GOOGLE",
        "DOMAIN-KEYWORD,google,GOOGLE",
        "DOMAIN-KEYWORD,youtube,GOOGLE",
        // Social / chat
        "DOMAIN-SUFFIX,twitter.com,PROXY",
        "DOMAIN-SUFFIX,x.com,PROXY",
        "DOMAIN-SUFFIX,twimg.com,PROXY",
        "DOMAIN-SUFFIX,t.co,PROXY",
        "DOMAIN-KEYWORD,twitter,PROXY",
        "DOMAIN-SUFFIX,facebook.com,PROXY",
        "DOMAIN-SUFFIX,fbcdn.net,PROXY",
        "DOMAIN-SUFFIX,instagram.com,PROXY",
        "DOMAIN-SUFFIX,cdninstagram.com,PROXY",
        "DOMAIN-SUFFIX,whatsapp.com,PROXY",
        "DOMAIN-SUFFIX,whatsapp.net,PROXY",
        "DOMAIN-SUFFIX,telegram.org,TELEGRAM",
        "DOMAIN-SUFFIX,telegram-cdn.org,TELEGRAM",
        "DOMAIN-SUFFIX,cdn-telegram.org,TELEGRAM",
        "DOMAIN-SUFFIX,telesco.pe,TELEGRAM",
        "DOMAIN-SUFFIX,t.me,TELEGRAM",
        "DOMAIN-SUFFIX,graph.org,TELEGRAM",
        "DOMAIN-SUFFIX,tdesktop.com,TELEGRAM",
        "DOMAIN-KEYWORD,telegram,TELEGRAM",
        "DOMAIN-SUFFIX,discord.com,PROXY",
        "DOMAIN-SUFFIX,discordapp.com,PROXY",
        // Dev / AI
        "DOMAIN-SUFFIX,github.com,PROXY",
        "DOMAIN-SUFFIX,githubusercontent.com,PROXY",
        "DOMAIN-SUFFIX,githubassets.com,PROXY",
        "DOMAIN-SUFFIX,cursor.sh,CURSOR",
        "DOMAIN-SUFFIX,cursor.com,CURSOR",
        "DOMAIN-SUFFIX,cursorapi.com,CURSOR",
        "DOMAIN-SUFFIX,cursor-cdn.com,CURSOR",
        "DOMAIN-SUFFIX,cursorvm.com,CURSOR",
        "DOMAIN-SUFFIX,anysphere.co,CURSOR",
        "DOMAIN-SUFFIX,anysphere.com,CURSOR",
        "DOMAIN-SUFFIX,anysphere.tech,CURSOR",
        "DOMAIN-KEYWORD,gcpp.cursor,CURSOR",
        "DOMAIN-SUFFIX,openai.com,PROXY",
        "DOMAIN-SUFFIX,chatgpt.com,PROXY",
        "DOMAIN-SUFFIX,anthropic.com,PROXY",
        "DOMAIN-SUFFIX,claude.ai,PROXY",
        // Binance / 币安 — sticky PROXY + real-IP DNS（见 DnsProfile.binanceFakeIPFilters）
        "DOMAIN-SUFFIX,binance.com,PROXY",
        "DOMAIN-SUFFIX,binance.me,PROXY",
        "DOMAIN-SUFFIX,binance.us,PROXY",
        "DOMAIN-SUFFIX,binance.cc,PROXY",
        "DOMAIN-SUFFIX,binance.co,PROXY",
        "DOMAIN-SUFFIX,binance.net,PROXY",
        "DOMAIN-SUFFIX,binance.org,PROXY",
        "DOMAIN-SUFFIX,binance.info,PROXY",
        "DOMAIN-SUFFIX,binance.vision,PROXY",
        "DOMAIN-SUFFIX,binance.cloud,PROXY",
        "DOMAIN-SUFFIX,binance.charity,PROXY",
        "DOMAIN-SUFFIX,binancezh.com,PROXY",
        "DOMAIN-SUFFIX,binancezh.pro,PROXY",
        "DOMAIN-SUFFIX,binancezh.net,PROXY",
        "DOMAIN-SUFFIX,binanceapi.com,PROXY",
        "DOMAIN-SUFFIX,binancefuture.com,PROXY",
        "DOMAIN-SUFFIX,binancecnt.com,PROXY",
        "DOMAIN-SUFFIX,binancecorp.com,PROXY",
        "DOMAIN-SUFFIX,binancecnl.com,PROXY",
        "DOMAIN-SUFFIX,binance-cdn.com,PROXY",
        "DOMAIN-SUFFIX,binanceavg.com,PROXY",
        "DOMAIN-SUFFIX,bnbstatic.com,PROXY",
        "DOMAIN-SUFFIX,nftstatic.com,PROXY",
        "DOMAIN-SUFFIX,bnappzh.com,PROXY",
        "DOMAIN-SUFFIX,bnappzh.co,PROXY",
        "DOMAIN-SUFFIX,bntrace.com,PROXY",
        "DOMAIN-SUFFIX,appsbinance.com,PROXY",
        "DOMAIN-SUFFIX,saasexch.com,PROXY",
        "DOMAIN-SUFFIX,saasexch.cc,PROXY",
        "DOMAIN-SUFFIX,ficus.cc,PROXY",
        "DOMAIN-KEYWORD,binance,PROXY",
        "DOMAIN-KEYWORD,bnbstatic,PROXY",
        "DOMAIN-KEYWORD,saasexch,PROXY",
        "DOMAIN-KEYWORD,nftstatic,PROXY",
        // Huobi / HTX — sticky PROXY + real-IP DNS（见 DnsProfile.huobiFakeIPFilters）
        "DOMAIN-SUFFIX,htx.com,PROXY",
        "DOMAIN-SUFFIX,huobi.com,PROXY",
        "DOMAIN-SUFFIX,huobi.pro,PROXY",
        "DOMAIN-SUFFIX,huobi.co,PROXY",
        "DOMAIN-SUFFIX,huobi.me,PROXY",
        "DOMAIN-SUFFIX,huobi.sc,PROXY",
        "DOMAIN-SUFFIX,huobipro.com,PROXY",
        "DOMAIN-SUFFIX,huobigroup.com,PROXY",
        "DOMAIN-SUFFIX,huobiapi.com,PROXY",
        "DOMAIN-SUFFIX,huobiasia.vip,PROXY",
        "DOMAIN-SUFFIX,hbfile.net,PROXY",
        "DOMAIN-SUFFIX,hbg.com,PROXY",
        "DOMAIN-SUFFIX,huobicdn.com,PROXY",
        "DOMAIN-KEYWORD,huobi,PROXY",
        "DOMAIN-KEYWORD,hbfile,PROXY",
        // Media
        "DOMAIN-SUFFIX,netflix.com,PROXY",
        "DOMAIN-SUFFIX,nflxvideo.net,PROXY",
        "DOMAIN-SUFFIX,spotify.com,PROXY",
        "DOMAIN-SUFFIX,tiktok.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokv.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokv.us,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn-us.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn-eu.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokcdn-in.com,TIKTOK",
        "DOMAIN-SUFFIX,tiktokd.net,TIKTOK",
        "DOMAIN-SUFFIX,tiktokd.org,TIKTOK",
        "DOMAIN-SUFFIX,tiktokmusic.app,TIKTOK",
        "DOMAIN-SUFFIX,tik-tokapi.com,TIKTOK",
        "DOMAIN-SUFFIX,ttlivecdn.com,TIKTOK",
        "DOMAIN-SUFFIX,ttlstatic.com,TIKTOK",
        "DOMAIN-SUFFIX,ttcdn-us.com,TIKTOK",
        "DOMAIN-SUFFIX,ttwebview.com,TIKTOK",
        "DOMAIN-SUFFIX,musical.ly,TIKTOK",
        "DOMAIN-SUFFIX,muscdn.com,TIKTOK",
        "DOMAIN-SUFFIX,byteoversea.com,TIKTOK",
        "DOMAIN-SUFFIX,byteoversea.net,TIKTOK",
        "DOMAIN-SUFFIX,byteintlapi.com,TIKTOK",
        "DOMAIN-SUFFIX,ibyteimg.com,TIKTOK",
        "DOMAIN-SUFFIX,ibytedtos.com,TIKTOK",
        "DOMAIN-SUFFIX,ipstatp.com,TIKTOK",
        "DOMAIN-SUFFIX,isnssdk.com,TIKTOK",
        "DOMAIN-SUFFIX,sgsnssdk.com,TIKTOK",
        // snssdk.com = 大陆抖音 DIRECT，勿写 TIKTOK
        "DOMAIN-KEYWORD,tiktok,TIKTOK",
        "DOMAIN-KEYWORD,tiktokcdn,TIKTOK",
        "DOMAIN-KEYWORD,byteoversea,TIKTOK",
        "DOMAIN-KEYWORD,ttlivecdn,TIKTOK",
        "DOMAIN-KEYWORD,isnssdk,TIKTOK",
        "DOMAIN-SUFFIX,reddit.com,PROXY",
        "DOMAIN-SUFFIX,redd.it,PROXY",
        // Common blocked
        "DOMAIN-SUFFIX,wikipedia.org,PROXY",
        "DOMAIN-SUFFIX,medium.com,PROXY",
        "DOMAIN-SUFFIX,dropbox.com,PROXY",
        "DOMAIN-SUFFIX,cloudflare.com,PROXY",
        "DOMAIN-SUFFIX,cloudfront.net,PROXY",
        // IPFoxy — purchase / gates must leave CN (Aliyun HK IPs often GEOIP,CN)
        "DOMAIN-SUFFIX,ipfoxy.com,PROXY",
        "DOMAIN-SUFFIX,ipfoxy.io,PROXY",
        "DOMAIN-KEYWORD,ipfoxy,PROXY",
    ]
}
