// Objective-C API for talking to github.com/bashx/mihomo-bridge Go package.
//   gobind -lang=objc github.com/bashx/mihomo-bridge
//
// File is generated by gobind. Do not edit.

#ifndef __Bridge_H__
#define __Bridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * ConfigureTUNPath selects runtime TUN options for real utun vs socketpair fallback.
socketPair=true  → packetFlow bridge (primary on modern iOS).
socketPair=false → BaoLianDeng-style utun fd.
 */
FOUNDATION_EXPORT void BridgeConfigureTUNPath(BOOL socketPair);

/**
 * ForceGC triggers GC for Network Extension memory budget.
 */
FOUNDATION_EXPORT void BridgeForceGC(void);

/**
 * GetDownloadTraffic returns download bytes.
 */
FOUNDATION_EXPORT int64_t BridgeGetDownloadTraffic(void);

/**
 * GetUploadTraffic returns upload bytes.
 */
FOUNDATION_EXPORT int64_t BridgeGetUploadTraffic(void);

/**
 * IsRunning reports engine state.
 */
FOUNDATION_EXPORT BOOL BridgeIsRunning(void);

/**
 * SetConfig writes YAML config into the home directory.
 */
FOUNDATION_EXPORT BOOL BridgeSetConfig(NSString* _Nullable yamlContent, NSError* _Nullable* _Nullable error);

/**
 * SetHomeDir sets Mihomo home directory (config + geo data).
 */
FOUNDATION_EXPORT void BridgeSetHomeDir(NSString* _Nullable path);

/**
 * SetLogFile appends mihomo engine logs to a shared file (tunnel.log).
 */
FOUNDATION_EXPORT BOOL BridgeSetLogFile(NSString* _Nullable path, NSError* _Nullable* _Nullable error);

/**
 * SetOutboundInterface forces dialer bind to Wi‑Fi/cellular (en0 / pdp_ip0).
Without this, Go sockets often follow the VPN default route into utun → no net.
 */
FOUNDATION_EXPORT void BridgeSetOutboundInterface(NSString* _Nullable name);

/**
 * SetTUNFd stores the TUN file descriptor from NEPacketTunnelProvider.
 */
FOUNDATION_EXPORT BOOL BridgeSetTUNFd(int32_t fd, NSError* _Nullable* _Nullable error);

/**
 * StartWithExternalController starts Mihomo with REST API enabled.
 */
FOUNDATION_EXPORT BOOL BridgeStartWithExternalController(NSString* _Nullable addr, NSString* _Nullable secret, NSError* _Nullable* _Nullable error);

/**
 * StopProxy shuts down the engine.
 */
FOUNDATION_EXPORT void BridgeStopProxy(void);

/**
 * TestDNSResolver sends a minimal A query to mihomo DNS listen address.
 */
FOUNDATION_EXPORT NSString* _Nonnull BridgeTestDNSResolver(NSString* _Nullable dnsAddr);

/**
 * TestDirectTCP dials via physical NIC (IP_BOUND_IF) — same as mihomo egress under VPN.
 */
FOUNDATION_EXPORT NSString* _Nonnull BridgeTestDirectTCP(NSString* _Nullable host, int32_t port);

/**
 * UpdateLogLevel sets mihomo log level.
 */
FOUNDATION_EXPORT void BridgeUpdateLogLevel(NSString* _Nullable level);

/**
 * ValidateConfig validates YAML without applying it.
 */
FOUNDATION_EXPORT BOOL BridgeValidateConfig(NSString* _Nullable yamlContent, NSError* _Nullable* _Nullable error);

/**
 * Version returns core version string.
 */
FOUNDATION_EXPORT NSString* _Nonnull BridgeVersion(void);

#endif
