
// Objective-C API for talking to the following Go packages
//
//	github.com/bashx/mihomo-bridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __MihomoCore_FRAMEWORK_H__
#define __MihomoCore_FRAMEWORK_H__

#include "Bridge.objc.h"
#include "Universe.objc.h"

#endif
